### ISSUE TITLE
Fler dokumentklasser

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/dsekdocs#7]
Just nu finns det två dokumentklasser: `dsekdoc` och `dsekregdoc`. Bör det finnas fler för t.ex. protokoll, motioner/propositioner, kallelser m.fl.? 

Fördelarna tänker jag är att det blir lättare att hålla en konsekvent stil för samma sorts dokument då (förhoppningsvis) de flesta använder klasserna för deras ändamål. 

Om detta är en bra idé tänker jag att resultatet blir ett slags arvträd:
```
dsek // paket, inte dokumentklass
└─ dsekdoc
   ├─ dsekparagraphed
   │  ├─ dsekminutes
   │  └─  dsekregdoc
   │      ├─ dsekregulations
   │      ├─ dsekstatutes
   │      ├─ dsekguideline
   │      └─ dsekpolicy
   ├─ dseknotice
   ├─ dseknominations
   └─ dsekmotion
``` 

```[tasklist]
### Tasks
- [x] `dsekmotion` (motion/proposition)
- [x] `dsekminutes` (protokoll)
- [x] `dsekdocket` (föredragningslista, kanske kombinera med kallelse?)
- [x] `dseknotice` (kallelse)
- [x] `dsekregulations` (reglemente)
- [x] `dsekstatues` (stadgar)
- [x] `dsekpolicy` (policyer)
- [x] `dsekguideline` (riktlinjer)
- [x] `dseknominations` (nomineringar, kanske kombinera med motion?)
```

**Comment by fnurkla** [comment]
Tack vare @alfredgrip har vi nu en `dsekmotion`(se #10). Känner att det är en indikation på att resterande klasser förmodligen också kommer att vara användbara.

**Comment by alfredgrip** [comment]
Håller med och tycker det hade varit nice med fler dokumetklasser, och arvträdet tycker jag ser väldigt rimligt ut!

Jag funderar också på om vi vill standardisera handlingar som innehåller valberedningens förslag eller exempelvis dokument såsom "Val av funktionärer inom Sexmästeriet". En av anledningarna till att standardisera alla typer av dokument är dels för minska förvirring i hur folk "bör" skapa ett slags dokument, men även att minska arbetsbördan att faktiskt skapa ett.

För dokument såsom "Val av funktionärer inom Sexmästeriet" handlar det mest om smidighet IMO, så kanske inte så hög prio, men för "valberedningens förslag" kan det vara bra att standardisera nu när vi ska föra statistik över val. Min tanke på hur ett sådant dokument kan se ut är att den kan innehålla en brödtext som eventuellt förklarar valförfarande eller en gruppmotivering om valet kräver en sådan, och sen någon form av lista för vem/vilka som är förslag till vilken/vilka post/poster, samt att på sista sidan i dokumentet presenterar man statistiken. I diskussionen när detta beslutet togs så oroade sig folk om att bli upptryckta med statistiken i ansiktet, men genom att presentera vem som är förslag till en post på en sida och statistiken på sista sidan så kan även de som endast vill veta vem ta del av detta, utan att behöva se statistiken.

Har du någon åsikt eller synpunkt om detta?

**Comment by fnurkla** [comment]
> Jag funderar också på om vi vill standardisera handlingar som innehåller valberedningens förslag eller exempelvis dokument såsom "Val av funktionärer inom Sexmästeriet". 
Värt att undersöka! Kanske att man har en najs environment som gör att definera 
> En av anledningarna till att standardisera alla typer av dokument är dels för minska förvirring i hur folk "bör" skapa ett slags dokument, men även att minska arbetsbördan att faktiskt skapa ett.
> 
> För dokument såsom "Val av funktionärer inom Sexmästeriet" handlar det mest om smidighet IMO, så kanske inte så hög prio, men för "valberedningens förslag" kan det vara bra att standardisera nu när vi ska föra statistik över val. Min tanke på hur ett sådant dokument kan se ut är att den kan innehålla en brödtext som eventuellt förklarar valförfarande eller en gruppmotivering om valet kräver en sådan, och sen någon form av lista för vem/vilka som är förslag till vilken/vilka post/poster, samt att på sista sidan i dokumentet presenterar man statistiken. I diskussionen när detta beslutet togs så oroade sig folk om att bli upptryckta med statistiken i ansiktet, men genom att presentera vem som är förslag till en post på en sida och statistiken på sista sidan så kan även de som endast vill veta vem ta del av detta, utan att behöva se statistiken.
> 
> Har du någon åsikt eller synpunkt om detta?

**Comment by fnurkla** [comment]
Jag undrar också om det är bra att dokumentklassen för protokoll ärver från `dsekregdoc` med tanke på hur protokollen som skrivs idag ser ut? Ska man kanske flytta ett par saker från `dsekregdoc` till `dsekdoc`? Eller slå ihop dem helt?

**Comment by fnurkla** [comment]
> Jag undrar också om det är bra att dokumentklassen för protokoll ärver från `dsekregdoc` med tanke på hur protokollen som skrivs idag ser ut? Ska man kanske flytta ett par saker från `dsekregdoc` till `dsekdoc`? Eller slå ihop dem helt?

Detta är löst i #15

**Comment by fnurkla** [comment]
Sedan 6672e0a finns det nu dokumentklasser för alla typer av styrdokument.

**Comment by fnurkla** [comment]
Med #20 och 85ee2d6 har vi nu en dokumentklass för kallelser.

**Comment by alfredgrip** [comment]
Funderar på ifall vi ska skapa en underklass till `dseknotice` för dokument som enbart innehåller en föredragningslista. Kallelser till sektionsmöten innehåller inte föredragningslistor utan kommer senare i ett separat dokument, så då känns det udda ifall man skulle använda sig av `dseknotice` för det och manuellt ändra t.ex. `shorttitle`. Tankar? Åsikter?

**Comment by fnurkla** [comment]
En PR för en `dsekminutes.cls` finns i #26

**Comment by fnurkla** [comment]
Med #26 mergead är det bara föredragningslistan kvar!

**Comment by fnurkla** [comment]
Då har vi officiellt alla sorters dokument som jag vet att vi har!!! Alla andra får vara egna issues, för nu stänger jag den här!
